"""Run a coding agent inside a container instead of on the host.

Isolation used to come from whatever switch each CLI exposed, and they expose
different things -- a seatbelt sandbox for one, a permission rule for another,
nothing at all for a third. The constraints therefore differed per agent, which
is why `tab:agent` cannot mark a best cell: a gap between two rows might be a
gap in scaffolding or a gap in what we managed to switch off. A container is
the same boundary for all of them.

What it closes, both measured open on the host first:

  * Reading a reference program by absolute path. A scratch working directory
    removes only the relative path; `workspace-write` restricts writes and the
    network, not reads. The container mounts the scratch directory and nothing
    else, so the reference programs are not merely unreadable, they are absent.
  * A shell that can reach the network. Egress is restricted to the single API
    host the agents call, so a shell inside has nowhere else to go.

Egress cannot simply be switched off: the CLI itself has to reach its model.
That asymmetry is why the host-side sandbox was never enough -- codex sandboxes
the shell it spawns, not itself, and claude sandboxes nothing.
"""

import json
import os
import shlex
import re
import subprocess
from pathlib import Path
from typing import Dict, List, Optional, Sequence

IMAGE = "datalogbench/agent:2026-09-zzz"   # pinned: a floating tag makes the row unreproducible
PROXY_IMAGE = "datalogbench/egress:2026-09"   # pinned for the same reason as IMAGE
NET_INTERNAL = "dlb-agent-int"     # no route off the host
NET_EGRESS = "dlb-agent-out"       # the proxy's own way out
PROXY_NAME = "dlb-egress"
PROXY_URL = f"http://{PROXY_NAME}:8888"
_REPO = Path(__file__).resolve().parent.parent

# The endpoint the direct-prompting experiments use. It is NOT automatically the
# endpoint an agent uses: each CLI has its own configuration, and on the machine
# this was first built the two agents were pointed at two other hosts entirely.
# Hard-coding one host here is what made the first isolation check vacuous -- it
# confirmed that a host nothing would dial was reachable. The allowlist is
# therefore derived from `agent_endpoints()` below, and `verify()` checks the
# endpoints the CLIs would actually use.
DIRECT_API_HOST = "api.zhizengzeng.com"
API_HOST = DIRECT_API_HOST   # kept for callers that mean the direct-prompt host

ALLOWLIST = _REPO / "docker" / "allow.txt"


def _host_of(url: str) -> Optional[str]:
    from urllib.parse import urlparse
    try:
        h = urlparse(url if "://" in url else "https://" + url).hostname
    except ValueError:
        return None
    return h


DEFAULT_AGENT_BASE_URLS = {
    # Single source of truth. These are passed to `docker build` as the base URLs
    # the CLIs are configured with (docker/codex.sh, docker/claude.sh) *and* used
    # to generate the proxy allowlist, so the two cannot disagree. When they were
    # two separate constants they did disagree, silently, and the isolation check
    # went green against an endpoint neither agent would contact.
    "codex": "https://api.zhizengzeng.com/v1",
    "claude": "https://api.zhizengzeng.com/anthropic",
}

AGENT_ENDPOINT_ENV = {
    "codex": "CODEX_BASE_URL",
    "claude": "ANTHROPIC_BASE_URL",
}

AGENT_API_KEY_ENV = "AGENT_API_KEY"


def agent_endpoints() -> Dict[str, str]:
    """Where each CLI sends its model calls, inside the container.

    Not read from the host's CLI configuration: the host's is irrelevant, since
    the container writes its own from these values at start-up. Reading the host
    would report a setting that does not run -- the same mistake as recording the
    host's CLI version for a run that happened in the image.
    """
    return {
        agent: os.environ.get(AGENT_ENDPOINT_ENV[agent], default)
        for agent, default in DEFAULT_AGENT_BASE_URLS.items()
    }


def allowlist_hosts() -> List[str]:
    """Hosts the proxy will let through: the agents' endpoints, nothing else."""
    hosts = []
    for url in agent_endpoints().values():
        h = _host_of(url)
        if h and h not in hosts:
            hosts.append(h)
    return hosts


def write_allowlist() -> List[str]:
    """Regenerate docker/allow.txt. The proxy mounts this file."""
    hosts = allowlist_hosts()
    ALLOWLIST.parent.mkdir(parents=True, exist_ok=True)
    body = "".join(f"^{re.escape(h)}$\n" for h in hosts)
    ALLOWLIST.write_text(
        "# Generated by agent_container.write_allowlist() -- do not edit.\n"
        "# One line per host the agent container may CONNECT to, port 443 only.\n"
        + body)
    return hosts

# Environment the agent needs. Nothing else is forwarded: the host environment
# holds keys for other services and a path layout that would only confuse a
# process inside the container.
# Agent inference has its own credential.  Direct prompting continues to use
# EVAL_API_KEY, so exhausting one setting cannot silently stop the other.  The
# key is inherited by name so its value never appears in Docker argv.
_PASS_ENV = (AGENT_API_KEY_ENV,)

# Non-secret runtime overrides are also inherited by name.  In particular this
# lets a pinned CLI image use a different provider without rebuilding it while
# keeping the effective endpoint, proxy allowlist, and provenance in sync.
_RUNTIME_CONFIG_ENV = tuple(AGENT_ENDPOINT_ENV.values()) + (
    "CODEX_MODEL", "ANTHROPIC_MODEL", "ANTHROPIC_SMALL_FAST_MODEL",
    "API_TIMEOUT_MS", "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC",
)

# Codex builds its Tokio runtime from the CPUs visible inside the container.
# On large hosts that can consume the entire container PID budget before the
# first model request is made (threads count toward the cgroup PID limit).
# Keep the worker count explicit so the run is reproducible across machines.
CODEX_TOKIO_WORKER_THREADS = "8"


class ContainerUnavailable(RuntimeError):
    """Docker is not usable, and the caller must decide rather than fall back.

    Falling back to the host would run the agent under the isolation the
    container was introduced to replace, and the results would be labelled as
    though they came from the container. That is worse than not running.
    """


def available() -> Optional[str]:
    """None when the container setting can run, else why it cannot."""
    try:
        p = subprocess.run(["docker", "info"], capture_output=True, text=True, timeout=20)
    except FileNotFoundError:
        return "docker is not installed"
    except subprocess.TimeoutExpired:
        return "docker info timed out"
    if p.returncode != 0:
        first = (p.stderr or p.stdout).strip().splitlines()
        return f"docker daemon unreachable: {first[-1][:120] if first else 'unknown'}"
    for img in (IMAGE, PROXY_IMAGE):
        q = subprocess.run(["docker", "image", "inspect", img],
                           capture_output=True, text=True, timeout=30)
        if q.returncode != 0:
            return f"image {img} not built (see docker/README.md)"
    for net in (NET_INTERNAL, NET_EGRESS):
        q = subprocess.run(["docker", "network", "inspect", net],
                           capture_output=True, text=True, timeout=30)
        if q.returncode != 0:
            return f"network {net} missing (see docker/README.md)"
    q = subprocess.run(["docker", "ps", "--filter", f"name=^{PROXY_NAME}$",
                        "--filter", "status=running", "--format", "{{.Names}}"],
                       capture_output=True, text=True, timeout=30)
    if PROXY_NAME not in q.stdout:
        return f"egress proxy {PROXY_NAME} is not running (see docker/README.md)"
    # The proxy is only as good as the list it is serving, and that list is
    # generated from CLI configuration that can change between runs. Compare
    # rather than assume: a stale allowlist either blocks the run or, worse,
    # permits a host the current configuration no longer justifies.
    if not os.environ.get(AGENT_API_KEY_ENV):
        return (f"{AGENT_API_KEY_ENV} is not set; coding-agent inference uses "
                "a credential independent of Direct prompting.")
    drift = image_endpoint_drift()
    if drift:
        return (f"image was built against different endpoints ({drift}); rebuild it, "
                "otherwise the allowlist and the CLI configuration disagree")
    want = set(allowlist_hosts())
    q = subprocess.run(["docker", "exec", PROXY_NAME, "cat", "/etc/tinyproxy/allow.txt"],
                       capture_output=True, text=True, timeout=30)
    got = {ln.strip().lstrip("^").rstrip("$").replace("\\", "")
           for ln in q.stdout.splitlines()
           if ln.strip() and not ln.startswith("#")}
    if got != want:
        return (f"proxy allowlist is stale: serving {sorted(got) or 'nothing'}, "
                f"configuration needs {sorted(want)}. Restart it: "
                f"python3 synthesis/agent_container.py --start-proxy")
    return None


def _word_size(version_text: str) -> Optional[int]:
    m = re.search(r"Word size:\s*(\d+)\s*bits", version_text or "")
    return int(m.group(1)) if m else None


def _souffle_identity(version_text: str) -> Optional[str]:
    """The parts of `souffle --version` that change how a program evaluates.

    Comparing only the word size was too narrow. Version and build options move
    semantics too -- a differently configured build can differ on aggregates or
    on which extensions exist -- and the point of the comparison is that the
    compiler giving a model its self-repair feedback is the compiler that grades
    it. Anything less than the whole identity leaves a way for them to differ.
    """
    if not version_text:
        return None
    keep = [ln.strip() for ln in version_text.splitlines()
            if ln.strip().startswith(("Version:", "Word size:", "Options enabled:"))]
    return " | ".join(keep) if keep else None


def image_endpoint_drift() -> Optional[str]:
    """Non-empty when the image's baked base URLs differ from AGENT_BASE_URLS.

    The allowlist is generated from the constants in this file; the CLIs inside
    the image are configured from whatever was passed at build time. If the two
    ever part company the isolation check goes green while the agent dials a host
    the proxy refuses -- or, worse, the proxy permits a host nothing justifies.
    Comparing them turns that into a startup error.
    """
    p = subprocess.run(
        ["docker", "image", "inspect", "--format", "{{json .Config.Env}}", IMAGE],
        capture_output=True, text=True, timeout=30)
    if p.returncode != 0:
        return None   # available() reports the missing image on its own
    env = dict(e.split("=", 1) for e in json.loads(p.stdout) if "=" in e)
    pairs = (("CODEX_BASE_URL", "codex"), ("ANTHROPIC_BASE_URL", "claude"))
    effective = {
        var: os.environ.get(var, env.get(var))
        for var, _agent in pairs
    }
    expected = agent_endpoints()
    bad = [f"{var}={effective.get(var, '<unset>')} != {expected[agent]}"
           for var, agent in pairs if effective.get(var) != expected[agent]]
    return "; ".join(bad) if bad else None


def image_provenance() -> Dict[str, str]:
    """What the image actually contains, for the run record.

    The agent row is the least reproducible of the three settings because it
    records what was requested rather than what was served. Reading the versions
    out of the image narrows that: the CLI build is pinned and inspectable.
    """
    out: Dict[str, str] = {"image": IMAGE}
    for key, cmd in (("codex_version", ["codex", "--version"]),
                     ("claude_version", ["claude", "--version"]),
                     ("souffle_version", ["souffle", "--version"])):
        # The entrypoint writes the CLI configuration before exec'ing, so even a
        # version probe needs a key present.  When a real key exists, ask Docker
        # to inherit it by name so its value never appears in argv or exception
        # messages.  The literal fallback is deliberately not a credential.
        key_arg = (AGENT_API_KEY_ENV if AGENT_API_KEY_ENV in os.environ
                   else f"{AGENT_API_KEY_ENV}=probe")
        p = subprocess.run(["docker", "run", "--rm", "--network", "none",
                            "-e", key_arg, "--entrypoint", "/bin/sh", IMAGE,
                            "-c", 'export EVAL_API_KEY="$AGENT_API_KEY"; '
                                  'exec /opt/dlb/agent-init.sh "$@"',
                            "agent-key-adapter", *cmd],
                           capture_output=True, text=True, timeout=60)
        text = (p.stdout or p.stderr).strip()
        if key == "souffle_version":
            out["souffle_version_full"] = text
            lines = [ln for ln in text.splitlines() if ln.startswith("Version:")]
            out[key] = (lines[0][:80] if lines else text.splitlines()[0][:80]) if p.returncode == 0 else "unknown"
        else:
            out[key] = text.splitlines()[0][:80] if p.returncode == 0 else "unknown"
    out["souffle_word_size"] = str(_word_size(out.get("souffle_version_full", "")) or "unknown")
    p = subprocess.run(["docker", "image", "inspect", "--format", "{{.Id}}", IMAGE],
                       capture_output=True, text=True, timeout=30)
    out["image_id"] = p.stdout.strip()[:19] if p.returncode == 0 else "unknown"
    return out


def start_proxy() -> List[str]:
    """(Re)start the egress proxy with an allowlist matching current config."""
    hosts = write_allowlist()
    subprocess.run(["docker", "rm", "-f", PROXY_NAME], capture_output=True, text=True)
    subprocess.run(
        ["docker", "run", "-d", "--name", PROXY_NAME, "--network", NET_INTERNAL,
         "-v", f"{ALLOWLIST}:/etc/tinyproxy/allow.txt:ro", PROXY_IMAGE],
        check=True, capture_output=True, text=True)
    subprocess.run(["docker", "network", "connect", NET_EGRESS, PROXY_NAME],
                   check=True, capture_output=True, text=True)
    return hosts


def build_command(argv: Sequence[str], workdir: Path,
                  network: str = NET_INTERNAL,
                  extra_env: Optional[Dict[str, str]] = None,
                  session_agent: Optional[str] = None) -> List[str]:
    """`docker run ...` wrapping `argv`, with only `workdir` mounted.

    The network is internal -- it has no route off the host -- so the proxy is
    the only way out, and the proxy forwards CONNECT to one host. Setting the
    proxy variables here rather than in the image keeps the allowlist visible in
    the command that runs.
    """
    if extra_env and any(key in _PASS_ENV for key in extra_env):
        raise ValueError(
            "credential environment variables must be inherited by name, "
            "not supplied through extra_env"
        )

    cmd = [
        "docker", "run", "--rm", "-i",
        "--network", network,
        # The scratch directory is the only mount. The repository -- and with it
        # every reference program -- is simply not present.
        "-v", f"{workdir}:/work",
        "-w", "/work",
        "--user", f"{os.getuid()}:{os.getgid()}",
        # Defence in depth for a process that runs model-written shell commands.
        "--cap-drop", "ALL",
        "--security-opt", "no-new-privileges",
        "--pids-limit", "512",
        "--memory", "4g",
    ]
    # Configuration, including the credential materialised by agent-init.sh,
    # stays on tmpfs. Both CLIs use one short-lived container per turn, so mount
    # only the selected CLI's non-secret session directory. The source is inside
    # the per-case scratch directory and is deleted after that case; no state
    # crosses case boundaries and no key is persisted on the host.
    cmd += ["--tmpfs", "/home/agent:rw,mode=1777", "-e", "HOME=/home/agent"]
    if session_agent:
        if session_agent not in {"codex", "claude"}:
            raise ValueError(f"unsupported session agent: {session_agent}")
        cmd += ["-v", f"{workdir / f'.{session_agent}-sessions'}:/sessions"]
    # Pass host credentials by name. Docker reads their values from this
    # process's environment without putting them in the child argv, which also
    # keeps subprocess errors and traces from disclosing them.
    for key in _PASS_ENV:
        if key in os.environ:
            cmd += ["-e", key]
    for key in _RUNTIME_CONFIG_ENV:
        if key in os.environ:
            cmd += ["-e", key]

    env: Dict[str, str] = {}
    # Session persistence wraps the actual CLI in ``sh -c ... exec \"$@\"``
    # before it reaches this function, so argv[0] is then ``sh`` rather than
    # ``codex``.  Key the resource contract off the explicit session identity
    # as well; otherwise Codex sees all 512 host CPUs, creates roughly one Tokio
    # worker per CPU, and exhausts the container's PID limit before its first
    # request.
    if session_agent == "codex" or (argv and Path(argv[0]).name == "codex"):
        env["TOKIO_WORKER_THREADS"] = CODEX_TOKIO_WORKER_THREADS
    if network == NET_INTERNAL:
        env.update({"HTTPS_PROXY": PROXY_URL, "HTTP_PROXY": PROXY_URL,
                    "https_proxy": PROXY_URL, "http_proxy": PROXY_URL})
    env.update(extra_env or {})
    for k, v in env.items():
        cmd += ["-e", f"{k}={v}"]
    # The currently deployed image predates the split credential and its baked
    # entrypoint still reads EVAL_API_KEY.  Adapt inside the container (not in a
    # host argv value): future images read AGENT_API_KEY directly, while setting
    # the legacy name here remains harmless and keeps this image resumable.
    cmd += [
        "--entrypoint", "/bin/sh", IMAGE,
        "-c", 'export EVAL_API_KEY="$AGENT_API_KEY"; '
              'exec /opt/dlb/agent-init.sh "$@"',
        "agent-key-adapter", *argv,
    ]
    return cmd


def verify(network: str) -> Dict[str, object]:
    """Test credential handling, isolation, endpoints, and compiler identity.

    Asserted rather than assumed, the same way the host sandbox was checked --
    the host sandbox is exactly what looked sufficient until someone ran `cat`
    on an absolute path.
    """
    import tempfile

    results: Dict[str, object] = {}
    golden = _REPO / "benchmark" / "query" / "Path.dl"
    with tempfile.TemporaryDirectory(prefix="agent_verify_") as tmp:
        work = Path(tmp)

        launch = build_command(["true"], work, network)
        secret = os.environ.get(AGENT_API_KEY_ENV, "")
        results["a_credential_not_in_argv"] = {
            "pass": bool(secret) and all(secret not in arg for arg in launch)
                    and AGENT_API_KEY_ENV in launch,
            "rc": 0,
            "output": "credential inherited by variable name" if secret else "missing key",
            "why": "the credential value must not appear in docker argv or process listings",
        }

        def run(argv, net=network, timeout=90):
            p = subprocess.run(build_command(argv, work, net),
                               capture_output=True, text=True, timeout=timeout)
            return p.returncode, (p.stdout + p.stderr).strip()

        rc, out = run(["cat", str(golden)])
        results["b_golden_unreadable"] = {
            "pass": rc != 0, "rc": rc, "output": out[:200],
            "why": "the reference program must not be reachable from inside"}

        rc, out = run(["curl", "-sS", "--max-time", "15", "https://github.com"])
        results["c_public_net_blocked"] = {
            "pass": rc != 0, "rc": rc, "output": out[:200],
            "why": "a shell inside must not reach the public internet"}

        # One check per agent, against the endpoint that agent is configured to
        # dial. A single check against a hard-coded host passed here while both
        # agents were pointed elsewhere -- it confirmed the reachability of a
        # host nothing would ever contact.
        for agent, url in sorted(agent_endpoints().items()):
            host = _host_of(url) or "?"
            rc, out = run(["curl", "-sS", "-o", "/dev/null", "-w", "%{http_code}",
                           "--max-time", "20", f"https://{host}/v1/models"])
            # Any HTTP response means the tunnel opened; 401 from an unauthenticated
            # probe is a reachable endpoint, not a failure of the boundary.
            results[f"d_api_reachable[{agent}]"] = {
                "pass": rc == 0, "rc": rc, "output": f"{host}: {out[:160]}",
                "why": f"{agent} must reach {host}, so this one must succeed"}

        (work / "t.dl").write_text(
            ".decl E(a:symbol,b:symbol)\n.input E\n.decl R(a:symbol,b:symbol)\n.output R\n"
            "R(x,y):-E(x,y).\nR(x,z):-R(x,y),E(y,z).\n")
        (work / "E.facts").write_text("a\tb\nb\tc\n")
        rc, out = run(["souffle", "-F", ".", "-D", ".", "t.dl"])
        produced = (work / "R.csv").exists() and (work / "R.csv").read_text().strip() != ""
        results["e_souffle_runs"] = {
            "pass": rc == 0 and produced, "rc": rc, "output": out[:200],
            "why": "the agent's only tool has to work"}

        # The agent validates its own program before submitting it, and the
        # harness grades with the host's compiler. If the two disagree on the
        # width of `number`, a program can pass inside and fail outside, and the
        # failure reads as the agent's. This is not hypothetical: the image was
        # first built with SOUFFLE_DOMAIN_64BIT against a 32-bit host, and the
        # benchmark had a demonstration whose expected output was int32
        # wraparound. The width is a property of how Soufflé was built, so
        # compare the builds rather than assume they agree.
        # The image's Souffle is the reference. Harness steps run against it
        # directly (docker/run-harness.sh); synthesis cannot -- it needs the
        # `openai` package and an endpoint, and the coding-agent path issues its
        # own docker commands -- so it uses the host's, and the host's has to be
        # the same build. Compare the whole version identity, not just the width:
        # the first version of this check compared widths alone, which is enough
        # to catch the 32-vs-64 case that motivated it and nothing else.
        rc, out = run(["souffle", "--version"])
        inside = _souffle_identity(out)
        host = subprocess.run(["souffle", "--version"], capture_output=True, text=True)
        outside = _souffle_identity(host.stdout) if host.returncode == 0 else None
        ok = inside is not None and inside == outside
        if outside is None:
            detail = ("no souffle on the host PATH -- install the same build the "
                      "image carries (\"Quick Start\" in the README)")
        elif ok:
            detail = f"both: {inside}"
        else:
            detail = f"image: {inside}   ||   host: {outside}"
        results["f_souffle_matches_host"] = {
            "pass": ok, "rc": rc, "output": detail,
            "why": ("synthesis grades on the host while the agent compiles in the "
                    "image; the two builds must be identical")}

    results["all_pass"] = all(v["pass"] for k, v in results.items() if k != "all_pass")
    return results


def main():
    import argparse
    ap = argparse.ArgumentParser(description="Container isolation for the coding-agent setting.")
    ap.add_argument("--verify", action="store_true", help="run the four isolation checks")
    ap.add_argument("--provenance", action="store_true", help="print the image's pinned versions")
    ap.add_argument("--start-proxy", action="store_true",
                    help="(re)start the egress proxy with an allowlist built from CLI config")
    ap.add_argument("--endpoints", action="store_true",
                    help="print where each agent CLI is configured to send model calls")
    ap.add_argument("--network", default=NET_INTERNAL, help="docker network the agent joins")
    args = ap.parse_args()

    if args.endpoints:
        for agent, url in sorted(agent_endpoints().items()):
            print(f"  {agent:8s} {url}   (allowlist host: {_host_of(url)})")
        return 0
    if args.start_proxy:
        hosts = start_proxy()
        print(f"[CONTAINER] {PROXY_NAME} restarted; allowlist: {', '.join(hosts)}")
        return 0

    why = available()
    if why:
        raise SystemExit(f"[CONTAINER] unavailable: {why}")
    if args.provenance:
        print(json.dumps(image_provenance(), indent=1))
        return 0
    if args.verify:
        res = verify(args.network)
        for name in sorted(k for k in res if k != "all_pass"):
            r = res[name]
            print(f"  {'PASS' if r['pass'] else 'FAIL'}  {name}  (rc={r['rc']})  {r['why']}")
            if not r["pass"]:
                print(f"        {r['output']}")
        print(f"\n[CONTAINER] {'all checks pass' if res['all_pass'] else 'NOT ISOLATED -- do not run the setting'}")
        return 0 if res["all_pass"] else 1
    ap.error("give --verify or --provenance")


if __name__ == "__main__":
    raise SystemExit(main())
